# Generated by Django 4.2.7 on 2025-09-17 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestations', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(help_text='Montant payé en FCFA')),
                ('moyen_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('carte_prepayee', 'Carte Prépayée'), ('espece', 'Espèce')], max_length=20)),
                ('operateur_mobile', models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money')], max_length=20, null=True)),
                ('numero_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='clients.client')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='prestations.prestation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TransactionExterne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fournisseur', models.CharField(max_length=50)),
                ('id_transaction_externe', models.CharField(max_length=100)),
                ('reponse_api', models.JSONField(blank=True, null=True)),
                ('statut_externe', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_externes', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Transaction Externe',
                'verbose_name_plural': 'Transactions Externes',
                'db_table': 'transactions_externes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
