# Generated by Django 4.2.7 on 2025-09-20 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_telephone', models.CharField(max_length=20)),
                ('client_nom', models.CharField(max_length=100)),
                ('client_prenom', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback Client',
                'verbose_name_plural': 'Feedbacks Clients',
                'db_table': 'client_feedbacks',
                'ordering': ['-date_creation'],
            },
        ),
    ]
