# Generated by Django 4.2.7 on 2025-09-17 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_qr', models.CharField(choices=[('identification', 'Identification Client'), ('prestation', 'Sélection Prestation'), ('paiement', 'Paiement'), ('recapitulatif', 'Récapitulatif')], max_length=20)),
                ('contenu', models.TextField(help_text='Contenu du QR code (JSON ou URL)')),
                ('statut', models.CharField(choices=[('genere', 'Généré'), ('scanne', 'Scanné'), ('expire', 'Expiré'), ('utilise', 'Utilisé')], default='genere', max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_scan', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('image_qr', models.ImageField(blank=True, help_text='Image du QR code généré', null=True, upload_to='qr_codes/')),
                ('nombre_scans', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='clients.client')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_codes',
                'ordering': ['-date_generation'],
            },
        ),
    ]
