# Generated by Django 4.2.7 on 2025-09-17 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_prestation', models.CharField(choices=[('dreadlocks_nouveau', 'Dreadlocks (nouveau)'), ('sister_locks', 'Sister locks'), ('nids_locks', 'Nids locks'), ('shampoing', 'Shampoing'), ('resserrage', 'Resserrage'), ('coiffure', 'Coiffure'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_min', models.PositiveIntegerField(help_text='Prix minimum en FCFA')),
                ('prix_max', models.PositiveIntegerField(blank=True, help_text='Prix maximum en FCFA (laisser vide si prix fixe)', null=True)),
                ('duree_estimee', models.PositiveIntegerField(blank=True, help_text='Durée estimée en minutes', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'db_table': 'prestations',
                'ordering': ['type_prestation', 'nom'],
            },
        ),
    ]
