# Generated by Django 4.2.7 on 2025-09-19 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Salon de Paiement', help_text='Le titre principal qui apparaît sur le site', max_length=200, verbose_name='Titre du site')),
                ('site_subtitle', models.CharField(default='Système de gestion de paiements', help_text='Le sous-titre qui apparaît sous le titre principal', max_length=300, verbose_name='Sous-titre du site')),
                ('welcome_message', models.TextField(default='Bienvenue sur votre espace de gestion', help_text="Message personnalisé pour la page d'accueil", verbose_name='Message de bienvenue')),
                ('logo', models.ImageField(blank=True, help_text='Format recommandé: PNG ou SVG avec fond transparent. Taille max: 2MB', null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])], verbose_name='Logo du site')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon pour le navigateur. Format recommandé: 32x32px ou 64x64px', null=True, upload_to='favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg'])], verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#FFD700', help_text='Couleur principale du thème (format hex: #FFD700)', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#E3F2FD', help_text='Couleur secondaire du thème (format hex: #E3F2FD)', max_length=7, verbose_name='Couleur secondaire')),
                ('contact_email', models.EmailField(blank=True, help_text='Email de contact affiché sur le site', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, help_text='Numéro de téléphone de contact', max_length=20, verbose_name='Téléphone de contact')),
                ('meta_description', models.TextField(default='Système de gestion de paiements pour salon', help_text='Description pour les moteurs de recherche', verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
