# Generated by Django 4.2.7 on 2025-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_size',
            field=models.CharField(choices=[('petite', 'Petite'), ('moyenne', 'Moyenne'), ('grande', 'Grande')], default='moyenne', help_text='Taille de police par défaut', max_length=10, verbose_name='Taille de police'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('clair', 'Clair'), ('sombre', 'Sombre'), ('auto', 'Auto')], default='auto', help_text="Thème de l'application", max_length=10, verbose_name='Thème'),
        ),
    ]
